version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: trafo_postgres
    restart: always
    environment:
      POSTGRES_USER: trafo
      POSTGRES_PASSWORD: trafo_pass
      POSTGRES_DB: trafo_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: trafo_redis
    restart: always
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    container_name: trafo_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"

volumes:
  db_data:
